services:

  postgres:
    image: postgres:14-alpine
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code

volumes:
  postgres_data: